{% set name = "CoolBox" %}
{% set version = "0.3.2" %}
 
package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/GangCaoLab/{{ name }}/archive/{{ version }}.tar.gz
  sha256: f64ad0af6b196c04d4d01f9b2c6cfe5f3d0d3819d5b7697b8e14eda517c60af4

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - h5py
    - pandas
    - matplotlib-base >=3.1.1
    - scipy >=1.0.0
    - cooler >=0.8.10
    - pairix
    - tabix
    - pybigwig
    - samtools >=1.10
    - jupyter >=1.0.0
    - ipywidgets >=7.5.1
    - intervaltree
    - dna_features_viewer
    - fire
    - nbformat
    - voila

test:
  imports:
    - coolbox

about:
  home: https://github.com/GangCaoLab/CoolBox
  license: GPL3
  license_file: LICENSE
  summary: Jupyter notebook based genomic data visulization toolkit.

extra:
  recipe-maintainers:
    - Nanguage
